name: Verify and sync

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        texlive: [latest, TL2022-historic, TL2021-historic, TL2020-historic]
        # 多版本 TexLive 兼容性测试
        # 版本号选自：https://hub.docker.com/r/texlive/texlive/tags
    container: texlive/texlive:${{ matrix.texlive }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Meta-data normalization
        run: python test/update-dist.py --dev --sha ${GITHUB_SHA}

      - name: run texlive docker container
        run: make doc test

      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v3
        with:
          name: Example-PDFs-texlive-${{ matrix.texlive }}
          path: |
            sustechthesis.pdf
            public-test/*.pdf

  sync:
    runs-on: ubuntu-latest
    name: Sync to other git service
    if: github.repository_owner == 'SUSTech-CRA'
    timeout-minutes: 10
    concurrency: 
      group: sync-job
      cancel-in-progress: true
    # needs: build_latex
    steps:

    - name: Push to sustech-git
      run: |
        tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
        echo $tmp_dir
        cd $tmp_dir
        git clone --bare "${GITHUB_REPO_URL}" this_repo
        cd this_repo
        git push --force --mirror "https://${USER}:${PERSONAL_TOKEN}@${REMOTE_REPO_URL}"
      env:
        USER: project_160_bot
        PERSONAL_TOKEN: ${{ secrets.GITLAB_PERSONAL_TOKEN }}
        GITHUB_REPO_URL: https://github.com/SUSTech-CRA/sustech-master-thesis.git
        REMOTE_REPO_URL: "mirrors.sustech.edu.cn/git/liziwl/sustech-master-thesis.git"
